import { buildFighter, createBattle, SeededRandom } from '/src/game-core.js';

const qs = (selector) => document.querySelector(selector);
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const state = { classes: null, balance: null, socket: null, playing: false, currentBattleId: null, fighters: new Map(), slots: new Map(), demoCounter: 0 };
const elements = {
  stage: qs('#battleStage'), status: qs('#roundStatus'), result: qs('#battleResult'), winnerName: qs('#winnerName'), winnerReward: qs('#winnerReward'), log: qs('#battleLog'), projectile: qs('#projectile'), impact: qs('#impact'), start: qs('#startBattle'), reset: qs('#resetBattle'), queue: qs('#queueCount'), connectionDot: qs('#connectionDot'), connectionText: qs('#connectionText'), form: qs('#testCommandForm'), user: qs('#testUser'), command: qs('#testCommand'), replies: qs('#chatReplies')
};
const slotElements = {
  left: { root: qs('#fighterLeft'), name: qs('#leftName'), className: qs('#leftClass'), level: qs('#leftLevel'), hpFill: qs('#leftHpFill'), hpText: qs('#leftHpText'), image: qs('#leftImage') },
  right: { root: qs('#fighterRight'), name: qs('#rightName'), className: qs('#rightClass'), level: qs('#rightLevel'), hpFill: qs('#rightHpFill'), hpText: qs('#rightHpText'), image: qs('#rightImage') }
};

function setFighter(slotName, fighter) {
  const slot = slotElements[slotName]; state.fighters.set(fighter.id, structuredClone(fighter)); state.slots.set(fighter.id, slotName);
  slot.name.textContent = fighter.username; slot.className.textContent = fighter.className; slot.level.textContent = `УР. ${fighter.level}`; slot.image.src = fighter.asset; slot.image.alt = `${fighter.className}: ${fighter.username}`; slot.root.className = `fighter-slot fighter-slot--${slotName}`; updateHp(fighter.id, fighter.hp, fighter.maxHp);
}
function updateHp(id, hp, maxHp) { const slot = slotElements[state.slots.get(id)]; if (!slot) return; const percent = Math.max(0, Math.min(100, hp / maxHp * 100)); slot.hpFill.style.width = `${percent}%`; slot.hpText.textContent = `${hp} / ${maxHp}`; const track = slot.hpFill.parentElement; track.setAttribute('aria-valuenow', String(hp)); track.setAttribute('aria-valuemax', String(maxHp)); }
function addLog(text) { const item = document.createElement('li'); item.textContent = text; elements.log.prepend(item); while (elements.log.children.length > 4) elements.log.lastElementChild.remove(); }
function addReply(text) { const item = document.createElement('li'); item.textContent = text; elements.replies.prepend(item); while (elements.replies.children.length > 6) elements.replies.lastElementChild.remove(); }
function clearMotion() { Object.values(slotElements).forEach((slot) => slot.root.classList.remove('is-approaching','is-attacking','is-ranged-attacking','is-hurt','is-dodging')); }
function floatText(id, text, className = '') { const slot = slotElements[state.slots.get(id)]; if (!slot) return; const label = document.createElement('span'); label.className = `damage-number ${className}`; label.textContent = text; slot.root.append(label); label.addEventListener('animationend', () => label.remove(), { once:true }); }
async function animateAttack(event) { const actorSlot = slotElements[state.slots.get(event.actorId)]; const targetSlotName = state.slots.get(event.targetId); if (event.role === 'melee') { actorSlot.root.classList.add('is-approaching'); await sleep(state.balance.battle.meleeApproachMs); actorSlot.root.classList.add('is-attacking'); await sleep(state.balance.battle.attackMs); } else { actorSlot.root.classList.add('is-ranged-attacking'); const direction = state.slots.get(event.actorId) === 'right' ? 'left' : 'right'; elements.projectile.className = `projectile is-flying-${direction}`; await sleep(state.balance.battle.projectileMs); elements.impact.style.left = targetSlotName === 'left' ? '34%' : '66%'; elements.impact.style.top = '55%'; elements.impact.classList.add('is-visible'); await sleep(120); } }
async function playSequence(events, battleId = null) { if (state.playing) return; state.playing = true; state.currentBattleId = battleId; elements.result.classList.remove('is-visible'); elements.log.replaceChildren(); for (const event of events) { if (event.type === 'battle:start') { setFighter('left', event.fighters[0]); setFighter('right', event.fighters[1]); elements.status.textContent = 'Бой начался'; addLog(`${event.fighters[0].username} против ${event.fighters[1].username}`); await sleep(900); } if (event.type === 'turn:start') { clearMotion(); elements.projectile.className = 'projectile'; elements.impact.className = 'impact'; elements.status.textContent = `Раунд ${event.turn}`; await sleep(state.balance.battle.turnDelayMs); } if (event.type === 'attack') await animateAttack(event); if (event.type === 'dodge') { const target = state.fighters.get(event.targetId); slotElements[state.slots.get(event.targetId)].root.classList.add('is-dodging'); floatText(event.targetId, 'УКЛОНЕНИЕ', 'is-dodge'); addLog(`${target.username} уклоняется от удара.`); await sleep(state.balance.battle.damagePauseMs); } if (event.type === 'damage') { const attacker = state.fighters.get(event.actorId); const target = state.fighters.get(event.targetId); target.hp = event.targetHp; updateHp(target.id, target.hp, target.maxHp); slotElements[state.slots.get(target.id)].root.classList.add('is-hurt'); floatText(target.id, event.critical ? `КРИТ -${event.damage}` : `-${event.damage}`, event.critical ? 'is-critical' : ''); addLog(`${attacker.username} наносит ${event.damage} урона${event.critical ? ' — критический удар!' : '.'}`); await sleep(state.balance.battle.damagePauseMs); } if (event.type === 'death') { clearMotion(); const loser = state.fighters.get(event.fighterId); slotElements[state.slots.get(event.fighterId)].root.classList.add('is-dead'); addLog(`${loser.username} повержен.`); await sleep(800); } if (event.type === 'battle:end') { const winner = state.fighters.get(event.winnerId); elements.status.textContent = 'Бой завершён'; elements.winnerName.textContent = winner.username; elements.winnerReward.textContent = `+${state.balance.progression.winnerXp} опыта`; elements.result.classList.add('is-visible'); await sleep(state.balance.battle.endPauseMs); } } state.playing = false; if (battleId && state.socket?.readyState === WebSocket.OPEN) state.socket.send(JSON.stringify({ type:'battle:complete', battleId })); }
function resetArena() { clearMotion(); Object.values(slotElements).forEach((slot) => slot.root.classList.remove('is-dead')); elements.result.classList.remove('is-visible'); elements.projectile.className = 'projectile'; elements.impact.className = 'impact'; elements.status.textContent = 'Ожидание бойцов'; elements.log.innerHTML = '<li>Арена ожидает новых претендентов.</li>'; }
function demoBattle() { if (state.playing) return; state.demoCounter += 1; const level = Math.min(12, 1 + state.demoCounter); const fighter1 = buildFighter({ id:'demo-left', username:'Asterion', classId:'gladiator', level }, state.classes); const fighter2 = buildFighter({ id:'demo-right', username:'FalconEye', classId:'hawkeye', level }, state.classes); const random = new SeededRandom(Date.now()); const battle = createBattle({ fighter1, fighter2, maxTurns:state.balance.battle.maxTurns, random:() => random.next() }); playSequence(battle.events); }
function connectSocket() { const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'; const socket = new WebSocket(`${protocol}//${location.host}/ws`); state.socket = socket; socket.addEventListener('open', () => { elements.connectionDot.classList.add('is-online'); elements.connectionText.textContent = 'Relay подключён'; }); socket.addEventListener('close', () => { elements.connectionDot.classList.remove('is-online'); elements.connectionText.textContent = 'Relay отключён. Повтор…'; setTimeout(connectSocket, 1600); }); socket.addEventListener('message', ({ data }) => { try { const message = JSON.parse(data); if (message.type === 'queue:update') elements.queue.textContent = String(message.players.length); if (message.type === 'battle:sequence') playSequence(message.events, message.battleId); if (message.type === 'chat:reply') addReply(message.message); } catch (error) { console.error(error); } }); }
function sendCommand(command = elements.command.value) { const username = elements.user.value.trim() || 'TestPlayer'; if (!state.socket || state.socket.readyState !== WebSocket.OPEN) return addReply('Relay ещё не подключён.'); state.socket.send(JSON.stringify({ type:'chat:command', userId:`test:${username.toLowerCase()}`, username, text:command })); elements.command.value = command; }
async function init() { [state.classes, state.balance] = await Promise.all([fetch('/config/classes.json').then((response) => response.json()), fetch('/config/balance.json').then((response) => response.json())]); if (new URLSearchParams(location.search).has('overlay')) document.body.classList.add('overlay-mode'); setFighter('left', buildFighter({ id:'preview-left', username:'Asterion', classId:'gladiator', level:1 }, state.classes)); setFighter('right', buildFighter({ id:'preview-right', username:'FalconEye', classId:'hawkeye', level:1 }, state.classes)); elements.start.addEventListener('click', demoBattle); elements.reset.addEventListener('click', resetArena); elements.form.addEventListener('submit', (event) => { event.preventDefault(); sendCommand(); }); document.querySelectorAll('[data-command]').forEach((button) => button.addEventListener('click', () => sendCommand(button.dataset.command))); connectSocket(); }
init().catch((error) => { console.error(error); elements.status.textContent = 'Ошибка загрузки'; });
